# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies and runtime deps
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

WORKDIR /app

# Copy project files
COPY . /app

# Install Python runtime dependencies
RUN pip install --no-cache-dir click python-dotenv

# Install the MCP server package
RUN pip install --no-cache-dir .

# Default command
CMD ["surveymars-mcp"]
